Initial SSL tunnel client implementation

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21,13 +21,13 @@ seds=[s/^#\(DEBUG\)/\1/]
 }';
 
 # Header files
-HEADERS="openssl/bio.h openssl/ssl.h openssl/err.h"
+HEADERS="openssl/bio.h openssl/ssl.h openssl/err.h casycom.h"
 
 # Libraries
-LIBS="ssl crypto"
+LIBS="ssl crypto casycom"
 
 # First pair is used if nothing matches
-PROGS="CC=gcc LD=ld INSTALL=install"
+PROGS="CC=gcc LD=ld AR=ar RANLIB=ranlib RANLIB=touch INSTALL=install"
 
 # Automatic vars
 [ -d .git ] && PKG_VERSTR=`git describe --always`
@@ -86,6 +86,7 @@ if [ "$SYSNAME" = "bsd" ]; then
     echo 's/-Wredundant-decls/-Wno-redundant-decls/g
 	s/-Winline/-Wno-inline/g' >>config.sed
 fi
+[ "$SYSNAME" = "linux" ] || echo 's/-p --ignore-fail-on-non-empty//g' >>config.sed
 if [ "$SYSNAME" = "linux" -o "$SYSNAME" = "bsd" ]; then
     echo 's/@SHBLDFL@/-shared -Wl,-soname=$1/g' >>config.sed
 fi
